const ON_SET_SELECTED_CITY_DATA = 'ON_SET_SELECTED_CITY_DATA';

const ON_REQUEST_FORECAST_PENDING = 'ON_REQUEST_FORECAST_PENDING';
const ON_REQUEST_FORECAST_SUCCESS = 'ON_REQUEST_FORECAST_SUCCESS';
const ON_REQUEST_FORECAST_FAILED = 'ON_REQUEST_FORECAST_FAILED';

export {
  ON_SET_SELECTED_CITY_DATA,
  ON_REQUEST_FORECAST_PENDING,
  ON_REQUEST_FORECAST_SUCCESS,
  ON_REQUEST_FORECAST_FAILED
};
