const ON_AUTOCOMPLETE_PENDING = 'ON_AUTOCOMPLETE_PENDING';
const ON_AUTOCOMPLETE_SUCCESS = 'ON_AUTOCOMPLETE_SUCCESS';
const ON_AUTOCOMPLETE_FAILED = 'ON_AUTOCOMPLETE_FAILED';

const ON_AUTOCOMPLETE_SELECTED = 'ON_AUTOCOMPLETE_SELECTED';
const ON_AUTOCOMPLETE_SELECTED_DATA = 'ON_AUTOCOMPLETE_SELECTED_DATA';

const ON_REQUEST_FORECAST_PENDING = 'ON_REQUEST_FORECAST_PENDING';
const ON_REQUEST_FORECAST_SUCCESS = 'ON_REQUEST_FORECAST_SUCCESS';
const ON_REQUEST_FORECAST_FAILED = 'ON_REQUEST_FORECAST_FAILED';

export {
  ON_AUTOCOMPLETE_PENDING,
  ON_AUTOCOMPLETE_SUCCESS,
  ON_AUTOCOMPLETE_FAILED,
  ON_AUTOCOMPLETE_SELECTED,
  ON_AUTOCOMPLETE_SELECTED_DATA,
  ON_REQUEST_FORECAST_PENDING,
  ON_REQUEST_FORECAST_SUCCESS,
  ON_REQUEST_FORECAST_FAILED
};
