const GLOBAL = {
  ON_AUTOCOMPLETE_PENDING: "ON_AUTOCOMPLETE_PENDING",
  ON_AUTOCOMPLETE_SUCCESS: "ON_AUTOCOMPLETE_SUCCESS",
  ON_AUTOCOMPLETE_FAILED: "ON_AUTOCOMPLETE_FAILED",
  ON_TEMPRATURE_UNITS_UPDATE: "ON_TEMPRATURE_UNITS_UPDATE",
  ON_DARK_MODE_UPDATE: "ON_DARK_MODE_UPDATE",
};

const FAVORITES = {
  ON_FAVORITES_UPDATE: "ON_FAVORITES_UPDATE",
};

const FORECAST = {
  ON_SET_SELECTED_CITY_DATA: "ON_SET_SELECTED_CITY_DATA",
  ON_REQUEST_FORECAST_PENDING: "ON_REQUEST_FORECAST_PENDING",
  ON_REQUEST_FORECAST_SUCCESS: "ON_REQUEST_FORECAST_SUCCESS",
  ON_REQUEST_FORECAST_FAILED: "ON_REQUEST_FORECAST_FAILED",
};

export { GLOBAL, FAVORITES, FORECAST };
