const ON_AUTOCOMPLETE_PENDING = 'ON_AUTOCOMPLETE_PENDING';
const ON_AUTOCOMPLETE_SUCCESS = 'ON_AUTOCOMPLETE_SUCCESS';
const ON_AUTOCOMPLETE_FAILED = 'ON_AUTOCOMPLETE_FAILED';

const ON_TEMPRATURE_UNITS_UPDATE = 'ON_TEMPRATURE_UNITS_UPDATE';
const ON_DARK_MODE_UPDATE = 'ON_DARK_MODE_UPDATE';

export {
  ON_AUTOCOMPLETE_PENDING,
  ON_AUTOCOMPLETE_SUCCESS,
  ON_AUTOCOMPLETE_FAILED,
  ON_TEMPRATURE_UNITS_UPDATE,
  ON_DARK_MODE_UPDATE
};
