const ON_AUTOCOMPLETE_PENDING = 'ON_AUTOCOMPLETE_PENDING';
const ON_AUTOCOMPLETE_SUCCESS = 'ON_AUTOCOMPLETE_SUCCESS';
const ON_AUTOCOMPLETE_FAILED = 'ON_AUTOCOMPLETE_FAILED';

export {
  ON_AUTOCOMPLETE_PENDING,
  ON_AUTOCOMPLETE_SUCCESS,
  ON_AUTOCOMPLETE_FAILED
};
