const ON_AUTOCOMPLETE_PENDING = 'ON_AUTOCOMPLETE_PENDING';
const ON_AUTOCOMPLETE_SUCCESS = 'ON_AUTOCOMPLETE_SUCCESS';
const ON_AUTOCOMPLETE_FAILED = 'ON_AUTOCOMPLETE_FAILED';
const ON_AUTOCOMPLETE_SELECTED = 'ON_AUTOCOMPLETE_SELECTED';
const ON_SELECTED_CURRENT_CONDITIONS = 'ON_SELECTED_CURRENT_CONDITIONS';
const ON_SELECTED_CURRENT_FORECAST = 'ON_SELECTED_CURRENT_FORECAST';

export {
  ON_AUTOCOMPLETE_PENDING,
  ON_AUTOCOMPLETE_SUCCESS,
  ON_AUTOCOMPLETE_FAILED,
  ON_AUTOCOMPLETE_SELECTED,
  ON_SELECTED_CURRENT_CONDITIONS,
  ON_SELECTED_CURRENT_FORECAST
};
